import { describe,it,expect } from 'vitest'
import { createActivityWorkout, planActivity, hybridSummary, mergeImportedActivities, activityEntries } from './activities.js'
import { trainingStreak } from './training-plan.js'
import { consistencyStats } from './consistency.js'
import { workoutNotificationPlan } from './workout-reminders.js'
const start=+new Date('2026-09-20T10:00:00'), now=start+3600000
const state=()=>({routines:[],customEx:[],workouts:[],week:{},dayPlan:{},unit:'kg',scheduleStarted:'2026-09-01',trainingStartDate:'2026-09-01'})
const record={id:'provider1',origin:'watch.app',start,end:start+1800000,type:'running',updatedAt:now}
describe('hybrid activity data flow',()=>{
 it('logs duration and optional metrics without strength volume',()=>{const s=state(),w=createActivityWorkout(s,{type:'running',start,minutes:30,distanceKm:5},now);expect(w.activity.averageHeartRate).toBeNull();expect(w.vol).toBe(0);expect(hybridSummary([w])).toMatchObject({running:1,strength:0,days:1,distanceKm:5,minutes:30})})
 it('rejects future, invalid and missing duration without inventing measurements',()=>{for(const minutes of [null,0,-3,1441,Infinity])expect(()=>createActivityWorkout(state(),{type:'running',start,minutes},now)).toThrow();expect(()=>createActivityWorkout(state(),{start:now,minutes:30},now)).toThrow();expect(()=>createActivityWorkout(state(),{start,minutes:30,averageHeartRate:4},now)).toThrow()})
 it('schedules recurring runs and matches logged activity to the planned routine',()=>{const s=state();const id=planActivity(s,{type:'running',minutes:30,weekdays:[0,2]},new Date(start));expect(s.week).toMatchObject({0:[id],2:[id]});s.workouts.push(createActivityWorkout(s,{type:'running',start,minutes:30},now));expect(s.workouts[0].routineId).toBe(id);expect(consistencyStats(s,'2026-09-20','2026-09-20',new Date(now))).toMatchObject({completed:1,extra:0})})
 it('combines strength and activity without replacing schedule or crediting a partial hybrid workout',()=>{const s=state();s.routines=[{id:'lift',name:'Lift',ex:[{id:'squat',sets:3}]}];s.week[0]='lift';planActivity(s,{type:'running',minutes:20,routineId:'lift'});expect(s.routines[0].ex).toHaveLength(2);expect(s.week[0]).toBe('lift');const w=createActivityWorkout(s,{type:'running',start,minutes:30,routineId:'lift'},now);expect(w.routineId).toBeNull();s.workouts=[w];s.reminder={on:true,time:'12:00',nextTime:'19:00'};expect(workoutNotificationPlan(s,new Date(now))[0]).toMatchObject({kind:'today',routineId:'lift'})})
 it('appends activities without overwriting an existing daily plan',()=>{const s=state();s.routines=[{id:'a',name:'A',ex:[]}];s.week[0]='a';const id=planActivity(s,{type:'running',minutes:30,weekdays:[0]},new Date(start));expect(s.week[0]).toEqual(['a',id]);expect(s.routines).toHaveLength(2)})
 it('imports once, reconciles manual entries, preserves notes and handles source updates',()=>{const s=state();s.workouts=[createActivityWorkout(s,{type:'running',start,minutes:30,distanceKm:5,note:'My route',rpe:6},now)];const id=s.workouts[0].id;expect(mergeImportedActivities(s,[record],'health-connect',now)).toMatchObject({updated:1,added:0});expect(mergeImportedActivities(s,[record],'health-connect',now)).toMatchObject({skipped:1});expect(mergeImportedActivities(s,[{...record,updatedAt:now+1,end:record.end+60000}],'health-connect',now)).toMatchObject({updated:1});expect(s.workouts).toHaveLength(1);expect(s.workouts[0]).toMatchObject({id,note:'My route',activity:{distanceKm:5,rpe:6}});expect(hybridSummary(s.workouts).minutes).toBe(31)})
 it('reconciles activities completed inside TGym, retains data on disconnect and after restart',()=>{const s=state();const id=planActivity(s,{type:'running',minutes:30,weekdays:[0]},new Date(start));const w=createActivityWorkout(s,{type:'running',start,minutes:30},now);delete w.activity;s.workouts=[w];mergeImportedActivities(s,[record],'health-connect',now);s.healthConnection={enabled:false};const reload=JSON.parse(JSON.stringify(s));expect(reload.workouts).toHaveLength(1);expect(reload.workouts[0].routineId).toBe(id);expect(reload.workouts[0].activity.source).toBe('health-connect')})
 it('keeps time and days unique across hybrid categories and ignores canceled sessions',()=>{const s=state();const w=createActivityWorkout(s,{type:'running',start,minutes:30,distanceKm:5},now);delete w.activity;w.entries.push({id:'squat',target:{mode:'reps'},sets:[{done:true,r:8,w:20}]});expect(hybridSummary([w,w,{...w,id:'cancel',finishReason:'cancelled'}])).toMatchObject({strength:1,running:1,minutes:30,days:1,distanceKm:5})})
 it('reconciles strength recorded by TGym and a watch without losing sets or counting twice',()=>{const s=state();s.workouts=[{id:'lift',name:'Lift',start,end:start+1800000,d:'2026-09-20',vol:100,entries:[{id:'squat',target:{mode:'reps'},sets:[{done:true,w:20,r:5}]}]}];mergeImportedActivities(s,[{...record,type:'strength'}],'health-connect',now);expect(s.workouts).toHaveLength(1);expect(s.workouts[0].entries[0].sets[0].w).toBe(20);expect(s.workouts[0].vol).toBe(100);expect(hybridSummary(s.workouts).strength).toBe(1)})
 it('keeps stable provider IDs even when timestamps change and ignores invalid records',()=>{const s=state();mergeImportedActivities(s,[record],'health-connect',now);mergeImportedActivities(s,[{...record,start:start-600000,updatedAt:now+1},{id:'bad'}],'health-connect',now);expect(s.workouts).toHaveLength(1);expect(s.workouts[0].start).toBe(start-600000)})
})

it('does not introduce missed days before a new recurring activity starts',()=>{const s=state();const date=new Date('2026-09-23T12:00:00');planActivity(s,{type:'running',minutes:30,weekdays:[3]},date);expect(consistencyStats(s,'2026-09-01','2026-09-23',date)).toMatchObject({planned:1,missed:0,pending:1});expect(trainingStreak(s,date).rows.filter(r=>r.planned)).toHaveLength(1)})
